import type { Metadata } from 'next';
import './globals.css';
import cx from 'classnames';
import { sfPro, inter } from './fonts';
import Footer from '@/components/landing/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cx(sfPro.variable, inter.variable)}>
        <main className='w-full h-full bg-slate-100'>{children}</main>
      </body>
    </html>
  );
}
